# SMTP (Mail Proxy)
server {
    listen 127.0.0.1:10026;

    proxy_pass mail.ruconet.internal:25;
    proxy_timeout 30m;

    proxy_ssl on;
    include /etc/nginx/snippets/ruconet-proxy.conf;
}

# Submission (Mail Proxy)
server {
    listen 127.0.0.1:10025;

    proxy_pass mail.ruconet.internal:10025;
    proxy_timeout 30m;

    proxy_ssl on;
    include /etc/nginx/snippets/ruconet-proxy.conf;
}

# IMAP (Mail Proxy)
server {
    listen 127.0.0.1:10143;

    proxy_pass mail.ruconet.internal:143;
    proxy_timeout 30m;

    proxy_ssl on;
    include /etc/nginx/snippets/ruconet-proxy.conf;
}
