# SMTP
server {
    listen 25;
    listen [::]:25;

    proxy_pass mail.ruconet.internal:25;
    proxy_protocol on;
    proxy_timeout 30m;

    proxy_ssl on;
    include /etc/nginx/snippets/ruconet-proxy.conf;
}

# Gitea (SSH)
server {
    listen 22;
    listen [::]:22;

    proxy_pass gitea.ruconet.internal:22;
    proxy_timeout 1h;

    proxy_ssl on;
    include /etc/nginx/snippets/ruconet-proxy.conf;
}
