# SMTP
server {
    listen 25;
    listen [::]:25;

    proxy_pass 127.0.0.1:10026;
    proxy_protocol on;
    proxy_timeout 30m;
}

# Gitea (SSH)
server {
    listen 22;
    listen [::]:22;

    proxy_pass gitea.ruconet.internal:22;
    proxy_timeout 1h;

    proxy_ssl on;
    include /etc/nginx/snippets/ruconet-proxy.conf;
}
