# SMTP (Onion)
server {
    listen 127.0.0.1:9025;

    proxy_pass mail.ruconet.internal:25;
    proxy_protocol on;
    proxy_timeout 30m;

    proxy_ssl on;
    include /etc/nginx/snippets/ruconet-proxy.conf;
}

# Gitea (SSH, Onion)
server {
    listen 127.0.0.1:9022;

    proxy_pass gitea.ruconet.internal:22;
    proxy_timeout 1h;

    proxy_ssl on;
    include /etc/nginx/snippets/ruconet-proxy.conf;
}
