# SMTP (Onion)
server {
    listen [::1]:9025 proxy_protocol;

    include /etc/nginx/snippets/onion.conf;

    proxy_pass 127.0.0.1:10026;
    proxy_protocol on;
    proxy_timeout 30m;
}

# Gitea (SSH, Onion)
server {
    listen [::1]:9022 proxy_protocol;

    include /etc/nginx/snippets/onion.conf;

    proxy_pass gitea.ruconet.internal:22;
    proxy_timeout 1h;

    proxy_ssl on;
    include /etc/nginx/snippets/ruconet-proxy.conf;
}
