# Mail Auth (Mail Proxy)
server {
    listen 127.0.0.1:10080;

    access_log off;

    location / {
        proxy_pass https://auth_backend;
        proxy_ssl_name mail.ruconet.internal;

        include /etc/nginx/snippets/ruconet-proxy.conf;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
