# Plaintext
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name nercone.dev       *.nercone.dev
                nerc1.dev         *.nerc1.dev
                diamondgotcat.net *.diamondgotcat.net
                d-g-c.net         *.d-g-c.net;

    return 301 https://$host$request_uri;
}

# Gitea (SSL/TLS)
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;

    server_name git.nercone.dev;

    include /etc/nginx/snippets/tls-http.conf;
    include /etc/nginx/snippets/backends/gitea.conf;
}

# Bluesky PDS (SSL/TLS)
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;

    server_name pds.nercone.dev;

    include /etc/nginx/snippets/tls-http.conf;
    include /etc/nginx/snippets/backends/pds.conf;
}

# Roundcube (SSL/TLS)
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;

    server_name mx.nercone.dev;

    include /etc/nginx/snippets/tls-http.conf;
    include /etc/nginx/snippets/backends/rspamd.conf;
    include /etc/nginx/snippets/backends/roundcube.conf;
}

# MTA-STS
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;

    server_name mta-sts.nercone.dev;

    include /etc/nginx/snippets/tls-http.conf;

    location = /.well-known/mta-sts.txt {
        default_type text/plain;
        add_header Cache-Control "max-age=2592000";
        return 200 "version: STSv1\r\nmode: enforce\r\nmx: mx.nercone.dev\r\nmax_age: 2592000\r\n";
    }

    location / {
        return 404;
    }
}

# SSL/TLS
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    listen 443 quic reuseport;
    listen [::]:443 quic reuseport;
    http2 on;

    server_name nercone.dev       *.nercone.dev
                nerc1.dev         *.nerc1.dev
                diamondgotcat.net *.diamondgotcat.net
                d-g-c.net         *.d-g-c.net;

    include /etc/nginx/snippets/tls-http.conf;
    include /etc/nginx/snippets/backends/website.conf;
}
