# Website (Onion)
server {
    listen [::1]:9080 proxy_protocol default_server;

    include /etc/nginx/snippets/onion-http.conf;
    include /etc/nginx/snippets/backends/website.conf;
}

# Gitea (Onion)
server {
    listen [::1]:9080 proxy_protocol;

    server_name "~^git\.[a-z2-7]{56}\.onion$";

    include /etc/nginx/snippets/onion-http.conf;
    include /etc/nginx/snippets/backends/gitea.conf;
}

# Bluesky PDS (Onion)
server {
    listen [::1]:9080 proxy_protocol;

    server_name "~^pds\.[a-z2-7]{56}\.onion$";

    include /etc/nginx/snippets/onion-http.conf;
    include /etc/nginx/snippets/backends/pds.conf;
}

# Roundcube (Onion)
server {
    listen [::1]:9080 proxy_protocol;

    server_name "~^mx\.[a-z2-7]{56}\.onion$";

    include /etc/nginx/snippets/onion-http.conf;
    include /etc/nginx/snippets/backends/rspamd.conf;
    include /etc/nginx/snippets/backends/roundcube.conf;
}
