# Website (Onion)
server {
    listen 127.0.0.1:9080 default_server;

    include /etc/nginx/snippets/backends/website.conf;
}

# Gitea (Onion)
server {
    listen 127.0.0.1:9080;

    server_name "~^git\.[a-z2-7]{56}\.onion$";

    include /etc/nginx/snippets/backends/gitea.conf;
}

# Bluesky PDS (Onion)
server {
    listen 127.0.0.1:9080;

    server_name "~^pds\.[a-z2-7]{56}\.onion$";

    include /etc/nginx/snippets/backends/pds.conf;
}

# Roundcube (Onion)
server {
    listen 127.0.0.1:9080;

    server_name "~^mx\.[a-z2-7]{56}\.onion$";

    include /etc/nginx/snippets/backends/rspamd.conf;
    include /etc/nginx/snippets/backends/roundcube.conf;
}
