include /etc/nginx/snippets/error.conf;

proxy_read_timeout 300s;
proxy_send_timeout 300s;

location / {
    proxy_pass https://gitea_backend;
    proxy_ssl_name gitea.ruconet.internal;
    include /etc/nginx/snippets/proxy.conf;
}
