include /etc/nginx/snippets/error.conf;

client_max_body_size 50m;

proxy_read_timeout 300s;
proxy_send_timeout 300s;

location / {
    proxy_pass https://roundcube_backend;
    proxy_ssl_name mail.ruconet.internal;
    include /etc/nginx/snippets/proxy.conf;
}
