include /etc/nginx/snippets/error.conf;

proxy_read_timeout 300s;
proxy_send_timeout 300s;

location ~* \.(ttf|otf|woff|woff2)$ {
    proxy_pass https://website_backend;
    proxy_ssl_name website.ruconet.internal;
    proxy_buffering off;
    include /etc/nginx/snippets/proxy.conf;
}

location / {
    proxy_pass https://website_backend;
    proxy_ssl_name website.ruconet.internal;
    include /etc/nginx/snippets/proxy.conf;
}
