server_name mx.nercone.dev;

auth_http         127.0.0.1:10080/auth;
auth_http_timeout 10s;

include /etc/nginx/snippets/tls-mail.conf;

proxy_pass_error_message off;
proxy_timeout 30m;

smtp_capabilities "PIPELINING" "8BITMIME" "ENHANCEDSTATUSCODES" "SIZE 52428800" "DSN";

smtp_auth plain login;
imap_auth plain login;

# Submission (TLS)
server {
    listen 465 ssl;
    listen [::]:465 ssl;

    protocol smtp;

    xclient         on;
    proxy_smtp_auth on;
}

# Submission (STARTTLS)
server {
    listen 587;
    listen [::]:587;

    protocol smtp;
    starttls only;

    xclient         on;
    proxy_smtp_auth on;
}

# IMAP (TLS)
server {
    listen 993 ssl;
    listen [::]:993 ssl;

    protocol imap;

    proxy_protocol on;
}

# IMAP (STARTTLS)
server {
    listen 143;
    listen [::]:143;

    protocol imap;
    starttls only;

    proxy_protocol on;
}
