# Submission (Onion)
server {
    listen [::1]:9587 proxy_protocol;

    protocol smtp;

    include /etc/nginx/snippets/onion.conf;

    xclient         off;
    proxy_smtp_auth on;
}

# IMAP (Onion)
server {
    listen [::1]:9143 proxy_protocol;

    protocol imap;

    include /etc/nginx/snippets/onion.conf;

    proxy_protocol on;
}
