# Submission (Onion)
server {
    listen 127.0.0.1:9587;

    protocol smtp;

    xclient         on;
    proxy_smtp_auth on;
}

# IMAP (Onion)
server {
    listen 127.0.0.1:9143;

    protocol imap;

    proxy_protocol on;
}
