include /etc/nginx/snippets/tls.conf;
include /etc/nginx/snippets/letsencrypt.conf;

ssl_ech_file /var/lib/ech/ech.nerc1.dev.pem;

ssl_session_cache shared:SSL:10m;

ssl_early_data off;

ssl_stapling off;
ssl_stapling_verify off;

add_header Alt-Svc 'h3=":443"; ma=3600' always;
add_header Onion-Location "http://$onion_host$request_uri" always;
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
